### ISSUE TITLE
supports_precompiled_qnn_onnx error generating Genie-compatible QNN binaries for Lllama 3.1 8b chat quantized

### ISSUE THREAD

**Issue by theoctopusride** [quic/ai-hub-apps#21]
I followed the instructions in the README file [here](https://github.com/quic/ai-hub-apps/tree/main/tutorials/llm_on_genie). This error didn't occur with either Llama 3-8b-chat or Llama 3.2 3b chat. The binaries were generated for both of those versions, but not for the Llama 3.1 8b chat quantized version.

After entering the following command, got the error pasted below

```
python3 -m qai_hub_models.models.llama_v3_1_8b_chat_quantized.export --device "Samsung Galaxy S24 (Family)" --skip-inferencing --skip-profiling --output-dir genie_bundle_llama-3.1-8b-chat-quantized
```

Error:
```
Traceback (most recent call last):
  File "/home/apps/miniconda3/envs/llm_on_genie/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/apps/miniconda3/envs/llm_on_genie/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/apps/miniconda3/envs/llm_on_genie/lib/python3.10/site-packages/qai_hub_models/models/llama_v3_1_8b_chat_quantized/export.py", line 57, in <module>
    main()
  File "/home/apps/miniconda3/envs/llm_on_genie/lib/python3.10/site-packages/qai_hub_models/models/llama_v3_1_8b_chat_quantized/export.py", line 34, in main
    parser = export_parser(
TypeError: export_parser() got an unexpected keyword argument 'supports_precompiled_qnn_onnx'
```

Let me know if you need additional information.

**Comment by gustavla** [comment]
Hi @theoctopusride, sorry for letting this issue go unanswered for so long (we are still establishing support structure and protocol, so apologies for the bumpy road). This is actually a bug that we fixed and pushed out around the time in late November/early December, so if you pull the latest `qai-hub-models` package and try again, it should work. Please re-open or file a new issue if you are still having issues.
