### ISSUE TITLE
 (ModuleNotFoundError: No module named 'qai-hub-models') when run Whisper on Snapdragon X Elite

### ISSUE THREAD

**Issue by mattchai** [quic/ai-hub-apps#7]
(whispter_test) C:\qualcomm\ai-hub-apps\apps\windows\python\Whisper>python -m qai-hub-models.models.whisper_base_en.export --target-runtime onnx
C:\qualcomm\whispter_test\Scripts\python.exe: Error while finding module specification for 'qai-hub-models.models.whisper_base_en.export' (ModuleNotFoundError: No module named 'qai-hub-models')

![image](https://github.com/user-attachments/assets/84f8b209-69ec-44b6-9645-f6f2cad25c68)

pip list:
Package             Version
------------------- -----------
asttokens           2.4.1
audio2numpy         0.1.2
backcall            0.2.0
backoff             2.2.1
beautifulsoup4      4.12.3
certifi             2024.8.30
charset-normalizer  3.4.0
colorama            0.4.6
coloredlogs         15.0.1
contextlib2         21.6.0
contourpy           1.3.0
cycler              0.12.1
decorator           5.1.1
deprecation         2.1.0
exceptiongroup      1.2.2
executing           2.1.0
ffmpeg              1.4
filelock            3.16.1
flatbuffers         24.3.25
fonttools           4.54.1
fsspec              2023.6.0
gdown               4.7.1
gitdb               4.0.11
GitPython           3.1.42
h5py                3.12.1
huggingface-hub     0.23.5
humanfriendly       10.0
idna                3.10
importlib-resources 6.4.5
iniconfig           2.0.0
ipython             8.12.3
jedi                0.19.1
jinja2              3.1.4
kiwisolver          1.4.7
MarkupSafe          3.0.2
matplotlib          3.7.5
matplotlib-inline   0.1.7
mpmath              1.3.0
networkx            3.2.1
numpy               1.23.1
onnx                1.17.0
onnxruntime         1.19.2
onnxruntime-qnn     1.19.0
opencv-python       4.8.1.78
packaging           23.2
pandas              1.5.3
parso               0.8.4
pickleshare         0.7.5
Pillow              10.0.1
pip                 20.2.3
pluggy              1.5.0
prettytable         3.9.0
prompt-toolkit      3.0.48
protobuf            3.20.2
pure-eval           0.2.3
pygments            2.18.0
pyparsing           3.2.0
pyreadline3         3.5.4
PySocks             1.7.1
pytest              7.4.2
python-dateutil     2.9.0.post0
pytz                2024.2
PyYAML              6.0.1
qai-hub             0.18.1
qai-hub-models      0.16.2
requests            2.32.3
requests-toolbelt   1.0.0
samplerate          0.2.1
schema              0.7.5
scipy               1.8.1
semver              3.0.2
setuptools          49.2.1
six                 1.16.0
smmap               5.0.1
soupsieve           2.6
stack-data          0.6.3
sympy               1.13.3
tabulate            0.9.0
tomli               2.0.2
torch               2.1.2
torchvision         0.16.2
tqdm                4.66.2
traitlets           5.14.3
typing-extensions   4.12.2
urllib3             1.26.18
wcwidth             0.2.13
zipp                3.20.2

**Comment by kory** [comment]
Hey Matt, could you try `python -m qai_hub_models.models whisper_base_en.export --target-runtime onnx`

The difference between this and the command above is `qai-hub-models` vs `qai_hub_models`. The name with underscores is the correct name.

**Comment by mattchai** [comment]
Hi Kory,

still got error as below, thanks.

(whispter_test) C:\qualcomm\ai-hub-apps\apps\windows\python\Whisper>python -m qai_hub_models.models whisper_base_en.export --target-runtime onnx
C:\qualcomm\whispter_test\Scripts\python.exe: No module named qai_hub_models.models.__main__; 'qai_hub_models.models' is a package and cannot be directly executed

**Comment by kory** [comment]
Sorry, I missed a period when I copied the above command:
```python -m qai_hub_models.models.whisper_base_en.export --target-runtime onnx`

**Comment by mattchai** [comment]
(whispter_test) C:\qualcomm\ai-hub-apps\apps\windows\python\Whisper>python -m qai_hub_models.models.whisper_base_en.export --target-runtime onnx
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python39\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\qualcomm\whispter_test\lib\site-packages\qai_hub_models\models\whisper_base_en\__init__.py", line 5, in <module>
    from qai_hub_models.models._shared.whisper.app import WhisperApp as App  # noqa: F401
  File "C:\qualcomm\whispter_test\lib\site-packages\qai_hub_models\models\_shared\whisper\app.py", line 12, in <module>
    import whisper  # type: ignore
ModuleNotFoundError: No module named 'whisper'

run pip install whisper, got another error
(whispter_test) C:\qualcomm\ai-hub-apps\apps\windows\python\Whisper>python -m qai_hub_models.models.whisper_base_en.export --target-runtime onnx
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python39\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\qualcomm\whispter_test\lib\site-packages\qai_hub_models\models\whisper_base_en\__init__.py", line 5, in <module>
    from qai_hub_models.models._shared.whisper.app import WhisperApp as App  # noqa: F401
  File "C:\qualcomm\whispter_test\lib\site-packages\qai_hub_models\models\_shared\whisper\app.py", line 12, in <module>
    import whisper  # type: ignore
  File "C:\qualcomm\whispter_test\lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
  File "C:\Program Files\Python39\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

**Comment by kory** [comment]
@mattchai What python version are you using? I'm unable to reproduce with Python 3.10 & 3.12 on my X Elite.

**Comment by mattchai** [comment]
@kory, my python version is 3.9, I will have a check on 3.10 later, thanks.

**Comment by mattchai** [comment]
@kory , still got error with python 3.10

![image](https://github.com/user-attachments/assets/353d692d-fbac-455f-805a-4fab58662bbb)



(aihub) C:\qualcomm\ai-hub-apps\apps\windows\python\Whisper>pip list
Package            Version
------------------ -----------
aiohappyeyeballs   2.4.3
aiohttp            3.11.7
aiosignal          1.3.1
asttokens          2.4.1
async-timeout      5.0.1
attrs              24.2.0
audio2numpy        0.1.2
backcall           0.2.0
backoff            2.2.1
beautifulsoup4     4.12.3
botocore           1.35.70
certifi            2024.8.30
charset-normalizer 3.4.0
colorama           0.4.6
coloredlogs        15.0.1
contextlib2        21.6.0
datasets           2.14.5
decorator          5.1.1
deprecation        2.1.0
dill               0.3.7
executing          2.1.0
ffmpeg             1.4
filelock           3.16.1
flatbuffers        24.3.25
frozenlist         1.5.0
fsspec             2023.6.0
gdown              4.7.1
gitdb              4.0.11
GitPython          3.1.42
h5py               3.12.1
huggingface-hub    0.23.5
humanfriendly      10.0
idna               3.10
ipython            8.12.3
jedi               0.19.2
Jinja2             3.1.4
jmespath           1.0.1
MarkupSafe         3.0.2
matplotlib-inline  0.1.7
mpmath             1.3.0
multidict          6.1.0
multiprocess       0.70.15
networkx           3.4.2
numpy              1.26.4
onnx               1.16.2
onnxruntime        1.20.1
onnxruntime-qnn    1.20.0
opencv-python      4.10.0.84
packaging          24.2
pandas             2.2.3
parso              0.8.4
pickleshare        0.7.5
pillow             11.0.0
pip                22.3.1
prettytable        3.11.0
prompt_toolkit     3.0.48
propcache          0.2.0
protobuf           3.20.3
pure_eval          0.2.3
pyarrow            18.1.0
Pygments           2.18.0
pyreadline3        3.5.4
PySocks            1.7.1
python-dateutil    2.9.0.post0
pytz               2024.2
PyYAML             6.0.2
qai-hub            0.20.0
qai-hub-models     0.19.0
requests           2.32.3
requests-toolbelt  1.0.0
s3transfer         0.10.4
samplerate         0.2.1
schema             0.7.5
semver             3.0.2
setuptools         65.5.0
six                1.16.0
smmap              5.0.1
soupsieve          2.6
stack-data         0.6.3
sympy              1.13.3
tabulate           0.9.0
torch              2.4.1
torchvision        0.19.1
tqdm               4.67.1
traitlets          5.14.3
typing_extensions  4.12.2
tzdata             2024.2
urllib3            2.2.3
wcwidth            0.2.13
xxhash             3.5.0
yarl               1.18.0

**Comment by kory** [comment]
Apologies we dropped this thread. Try `pip install openai-whisper==20231117`
